export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_ERROR = 'VERIFY_ERROR';
export const REVERIFY_SUCCESS = 'REVERIFY_SUCCESS';
export const REVERIFY_ERROR = 'REVERIFY_ERROR';

/** AUTHORIZATION */
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';
