export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const VERIFY_SUCCESS = 'VERIFY_SUCCESS';
export const VERIFY_ERROR = 'VERIFY_ERROR';
export const REVERIFY_SUCCESS = 'REVERIFY_SUCCESS';
export const REVERIFY_ERROR = 'REVERIFY_ERROR';

// AUTHORIZATION
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_ERROR = 'AUTHORIZATION_ERROR';

// PASSWORD RESET
export const RESET_PASSWORD_SENT = 'RESET_PASSWORD_SENT';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';

// ERROR
export const SERVER_ERROR = 'SERVER_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';

// USER ROLE ACTION TYPES
export const ASSIGN_SUCCESS = 'ASSIGN_SUCCESS';
export const ASSIGN_FAILED = 'ASSIGN_FAILED';

// ADDING AN ACCOMMODATION SUPPLIER
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_ERROR = 'ADD_SUPPLIER_ERROR';

// ACCOMMODATIONS
export const GET_ACCOMMODATIONS_SUCCESS = 'GET_ACCOMMODATIONS_SUCCESS';
export const GET_ACCOMMODATIONS_FAILURE = 'GET_ACCOMMODATIONS_SUCCESS';
export const GET_ACCOMMODATION_SUCCESS = 'GET_ACCOMMODATION_SUCCESS';
export const GET_ACCOMMODATION_FAILURE = 'GET_ACCOMMODATION_FAILURE';
export const ADD_ACCOMMODATION_SUCCESS = 'ADD_ACCOMMODATION_SUCCESS';
export const ADD_ACCOMMODATION_FAILURE = 'ADD_ACCOMMODATION_FAILURE';
export const RATE_ACCOMMODATION_SUCCESS = 'RATE_ACCOMMODATION_SUCCESS';
export const RATE_ACCOMMODATION_FAILED = 'RATE_ACCOMMODATION_FAILED';
export const ADD_ROOMS_SUCCESS = 'ADD_ROOMS_SUCCESS';
export const ADD_ROOMS_FAILURE = 'ADD_ROOMS_FAILURE';

// LOCATIONS
export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_LOCATIONS_ERROR = 'FETCH_LOCATIONS_ERROR';

// LIKE
export const LIKE_SUCCESS = 'LIKE_SUCCESS';
export const LIKE_ERROR = 'LIKE_ERROR';

// FEEDBACK
export const FEEDBACK_SUCCESS = 'FEEDBACK_SUCCESS';
export const FEEDBACK_ERROR = 'FEEDBACK_ERROR';

//PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';

// REQUESTS
export const FETCH_REQUESTS = 'FETCH_REQUESTS';
export const FETCH_REQUESTS_FAILED = 'FETCH_REQUESTS_FAILED';
export const REQUEST_TRIP_SUCCESS = 'REQUEST_TRIP_SUCCESS';
export const REQUEST_TRIP_ERROR = 'REQUEST_TRIP_ERROR';
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS';
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR';
export const UPDATE_REQUEST_SUCCESS = 'UPDATE_REQUEST_SUCCESS';
export const UPDATE_REQUEST_ERROR = 'UPDATE_REQUEST_ERROR';
export const DELETE_REQUEST_SUCCESS = 'DELETE_REQUEST_SUCCESS';
export const DELETE_REQUEST_ERROR = 'DELETE_REQUEST_ERROR';
export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_PAST = 'FETCH_PAST';
